[project]
name = "pokedex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "marimo>=0.13.15",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
